Add support for B3 Propagation
signalfx/jaeger-client-ruby pull request #2
Opened 2018-11-14 13:09 UTC by achandras

2018-11-15 18:37 UTC, keitwb commented on lib/jaeger/client/tracer.rb
> +    FORMAT_B3 = 4
Make this a higher number so it doesn't risk conflicting with any other OT formats if they get updated.

2018-11-15 18:39 UTC, keitwb commented on lib/jaeger/client/tracer.rb
> +          trace_id = TraceId.base16_hex_id_to_uint64(carrier['X-B3-TraceId'])
Will this also handle lower case headers?  HTTP HEader names are technically case-insensitive.

2018-11-15 18:41 UTC, keitwb commented on spec/jaeger/client/tracer_spec.rb
> +        let(:carrier) { { 'X-B3-TraceId' => trace_id,
Add a test for all lowercase header names.

2018-11-15 19:00 UTC, achandras commented on lib/jaeger/client/tracer.rb
> +          trace_id = TraceId.base16_hex_id_to_uint64(carrier['X-B3-TraceId'])
Would it be ok to assume that they'll come in all lowercase? I'd like to avoid converting the hash to a case-insensitive one or to try iterating through the keys, if possible.

2018-11-15 19:12 UTC, keitwb commented on lib/jaeger/client/tracer.rb
> +          trace_id = TraceId.base16_hex_id_to_uint64(carrier['X-B3-TraceId'])
I have no idea what behavior the Ruby HTTP libs have.  The carrier key lookup might have some magic in it that makes it already case-insensitive but you definitely need to confirm.  The automated tests with different casing will be essential here.

2018-11-15 19:56 UTC, achandras commented on lib/jaeger/client/tracer.rb
> +          trace_id = TraceId.base16_hex_id_to_uint64(carrier['X-B3-TraceId'])
The carrier is only a hash, so I'll have to check the keys manually

2018-11-15 20:26 UTC, achandras commented on spec/jaeger/client/tracer_spec.rb
> +          let(:carrier_lowercase) { Net::HTTPResponse.new({}, 200, "") }
My reasoning here is that except for Rack, which is the most common interface, most other requests being extracted should be done by Net::HTTP or a wrapper of that.

The Net::HTTPHeader module provides case-insensitive lookup.

I feel that this covers most, if not all, of the cases where headers would be extracted in Ruby. The `opentracing-ruby` project also uses Net::HTTP in their example. So we either get a (case-sensitive) hash from Rack or a case-insensitive Net::HTTPHeader.

If this is not comprehensive enough, I will add the manual iteration/key check as a fallback approach. I just feel like that would be a very costly option

2018-11-20 14:24 UTC, achandras commented
@keitwb @mpetazzoni I think I now understand a bit better how these formats should interact in OpenTracing Ruby. I've pulled out the B3 changes into a separate subclass of tracer as well to make it cleaner.

Could you please take a look and let me know what you think?

2018-11-20 15:03 UTC, keitwb commented
This looks wrong.  Usually the propagation logic is composed with the tracer class via some config option instead of being defined by inheritance of the tracer class.

2018-11-20 15:04 UTC, keitwb commented
> This looks wrong. Usually the propagation logic is composed with the tracer class via some config option instead of being defined by inheritance of the tracer class.

E.g. https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/Configuration.java#L455

2018-11-20 15:07 UTC, keitwb commented on lib/jaeger/client/tracer_b3.rb
> +    class TracerB3 < Jaeger::Client::Tracer
Just make a "propagation" class for each one of these formats and then assign it to some field in the Jaeger tracer and proxy through the inject/extract methods.

2018-11-20 15:08 UTC, keitwb commented on lib/jaeger/client.rb
> +      if propagate_b3
This is fine to have this config option, but just make a single tracer instance regardless and populate a "propagation codec" field with an instance that does the inject/extract logic and is called by the tracer's inject/extract methods.

2018-11-27 20:00 UTC, mpetazzoni requested changes

2018-11-27 20:00 UTC, mpetazzoni commented on lib/jaeger/client/propagation_codec/b3_codec.rb
> +          carrier['x-b3-traceid'] = span_context.trace_id.to_s(16)
Trace IDs may be 128-bit / 32-character hexadecimal

2018-11-27 20:00 UTC, mpetazzoni commented on lib/jaeger/client/propagation_codec/b3_codec.rb
> +          carrier['x-b3-sampled'] = span_context.flags.to_s(16)
What about X-B3-Flags?

2018-11-27 20:00 UTC, mpetazzoni commented on lib/jaeger/client/propagation_codec/jaeger_codec.rb
> +            span_context.trace_id.to_s(16),
ditto about trace ID length

2018-11-27 20:31 UTC, achandras commented on lib/jaeger/client/propagation_codec/b3_codec.rb
> +          carrier['x-b3-traceid'] = span_context.trace_id.to_s(16)
The argument to `to_s` is the radix for a hex string.

Do we need to ensure a 32 char length to the string?

2018-11-27 20:32 UTC, achandras commented on lib/jaeger/client/propagation_codec/b3_codec.rb
> +          carrier['x-b3-sampled'] = span_context.flags.to_s(16)
Slipped my notice.

Will add that, thanks

2018-11-28 14:25 UTC, keitwb commented on lib/jaeger/client/propagation_codec/b3_codec.rb
> +          carrier['x-b3-traceid'] = span_context.trace_id.to_s(16)
No, they can be at most 32 chars in hex but a lot of times are only 16 chars (64 bit).

2018-11-28 14:26 UTC, keitwb commented on lib/jaeger/client/propagation_codec/b3_codec.rb
> +          carrier['x-b3-traceid'] = span_context.trace_id.to_s(16)
We have normalization on the server side that will pad hex strings if they have leading zeros stripped, but it would be best if you just outputted the pre-padded hex strings from here for better compatibility with other backends and tracers.

2018-11-28 14:27 UTC, keitwb commented on lib/jaeger/client/propagation_codec/b3_codec.rb
> +          carrier['x-b3-traceid'] = span_context.trace_id.to_s(16)
E.g. if the trace id is 64 bit and was the value `10` it should make the trace id `000000000000000a` instead of just `a`.

2018-11-28 14:29 UTC, keitwb commented on lib/jaeger/client/propagation_codec/b3_codec.rb
> +          carrier['x-b3-traceid'] = span_context.trace_id.to_s(16)
Also for ids that are only 16 bits, don't just make them padded to 32 chars with 16+ leading 0s.

2018-11-28 20:33 UTC, keitwb commented on lib/jaeger/client/propagation_codec/jaeger_codec.rb
> +            span_context.trace_id.to_s(16),
This is preexisting code that was rearranged so I would not modify it since we don't use this old Uber propagation scheme.

2018-11-28 20:33 UTC, keitwb approved these changes

2018-11-30 23:56 UTC, mpetazzoni approved these changes
LGTM if @keitwb also likes it

2018-12-03 22:20 UTC, merged